-- ╔══════════════════════════════════════════════════════════════════════╗
-- ║  NO EJECUTAR. Quedó obsoleto sin llegar a usarse.                    ║
-- ╚══════════════════════════════════════════════════════════════════════╝
--
-- La cuenta que este archivo borra resultó estar creada con el correo real
-- del dueño de la app, así que al activar el login se convirtió sin más en
-- su cuenta de usuario: es con la que entra, y guarda los entrenamientos
-- importados de sus notas, los pesajes y el plan.
--
-- Ejecutarlo hoy no limpia nada de desarrollo: le borra su cuenta y, en
-- cascada, todos sus datos. Se conserva solo como registro de la etapa
-- anterior.
--
-- Para vaciar los datos de entrenamiento sin tocar la cuenta está
-- `0018_reset_training_data.sql`.
--
-- ----------------------------------------------------------------------
-- Contenido original, a partir de aquí:
--
-- Elimina el usuario de desarrollo y todo lo suyo.
--
-- Se ejecuta cuando la app con login ya funciona y no queda nada que
-- conservar de la etapa anterior.
--
-- Basta con borrar la cuenta: todas las tablas cuelgan de `auth.users` con
-- borrado en cascada, así que se van con ella el perfil, los planes, las
-- sesiones, las series, los pesos, la conversación y el reparto semanal.
--
-- Usa el UUID literal y no `dev_user_id()` a propósito: esa función la
-- elimina 0024, y así este archivo funciona se ejecute antes o después.
--
-- ⚠️ No hay vuelta atrás.

-- Comentado a propósito: ese id es hoy la cuenta real del usuario.
-- Si algún día hiciera falta de verdad, descomenta sabiendo lo que borras.
--
-- delete from auth.users
-- where id = 'f4707a48-313f-4fe6-9ee2-0a8d09973167';

-- Comprobación: debe devolver cero filas en todas.
-- select
--   (select count(*) from public.workout_sessions)  as sesiones,
--   (select count(*) from public.workout_plans)     as planes,
--   (select count(*) from public.body_weight_entries) as pesos,
--   (select count(*) from public.coach_messages)    as mensajes,
--   (select count(*) from public.weekly_splits)     as repartos;
